server {
    listen 10000;
    server_name _;

    client_max_body_size 20M;

    location /socket.io/ {
        proxy_pass https://uat-brisa-padel-server.onrender.com;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host brisa-padel-server.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ ^/(api|auth)/ {
        proxy_pass https://uat-brisa-padel-server.onrender.com;
        proxy_ssl_server_name on;
        proxy_redirect off;
        proxy_set_header Host brisa-padel-server.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ ^/v1/ {
        proxy_pass https://uat-brisa-padel-server.onrender.com;
        proxy_ssl_server_name on;
        proxy_redirect off;
        proxy_set_header Host brisa-padel-server.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass https://uat-brisa-padel-web.onrender.com;
        proxy_ssl_server_name on;
        proxy_redirect off;
        proxy_set_header Host brisa-padel-web-1.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}